stages:
- Build
- deploy
- review
- dast
- Package
- staging
- canary
- production
- performance
- cleanup
- test


#default:
#  before_script:
#    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST


compile:
  stage: Build
  tags:
    - dck
  image:
    name: harbor.lab.com/library/make:v1.1
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin'
  script:
    - make all
  artifacts:
    paths:
    - bin/facebooc
#    untracked: true
#    when: on_success
    expire_in: "7 days"



image build:
  stage: Package
  tags:
    - local
  script:
    - docker image build -t "${HARBOR_HOST}/${HARBOR_PROJECT}/fb:${CI_COMMIT_TAG}" -f fb.Dockerfile .
  dependencies:
    - compile
  needs:
    - job: compile
      artifacts: true


upload to registry:
  stage: test
  tags:
    - local
  script:
    - docker login -u $HARBOR_USERNAME -p $HARBOR_PASSWORD $HARBOR_HOST
    - docker push "${HARBOR_HOST}/${HARBOR_PROJECT}"/fb:33 #${CI_COMMIT_TAG}"


deploy:
  tags:
    - local
  environment: test
  script:
    - echo $KUBECONFIG
    - kubectl config get-contexts
    - kubectl config use-context kind-dev 
    - kubectl get no
    - cd "$(pwd)/k8s/"
    - kubectl apply -f fb.yml -n test
